python -u main.py  \
    --train_pkl ../data/train-token-term.jl  \
    --valid_pkl ../data/valid-token-term.jl  \
    --pred_pkl ../data/EntityPairItems-disodiso-gold-500-token-term.jl  \
    --dict ../data/cui2idx.pkl  \
    --tokenizer monologg/biobert_v1.1_pubmed  \
    --model monologg/biobert_v1.1_pubmed  \
    --output_path output \
    --sampleNum 1  \
    --maxLength 3  \
    --testRate 0.2  \
    --trainBatchSize 512  \
    --testBatchSize 512  \
    --weightDecay 1e-8  \
    --accumulate_step 1 \
    --epoch 100  \
    --lr 1e-3  \
    --gamma 0.9  \
    --nworkers 4  \
    --pinMemory False \
    --graphPath ../data/ \
    --initEmbedding embedtable.npy \
    --do_train True \
    --do_eval True \
    --do_pred True \
    --init_embedding True \
    --valid_epoch 10 \
    --cuda 1
